abouts/urls.py
# encoding: utf-8
"""
@author: Sunmouren
@contact: sunxuechao1024@gmail.com
@time: 2019/3/17 17:08
@desc: 
"""

from django.urls import path

from .views import AboutDetail

app_name = 'abouts'


urlpatterns = [
   path('us/', AboutDetail.as_view(), name='about-us'),
]

courses/urls.py
# encoding: utf-8
"""
@author: Sunmouren
@contact: sunxuechao1024@gmail.com
@time: 2019/2/16 20:36
@desc: 
"""
from django.urls import path

from .views import CourseList, CourseDetail, VideoDetail, course_search, UploadCourse, UploadVideo

app_name = 'courses'


urlpatterns = [
    path('list/', CourseList.as_view(), name='course-list'),
    path('detail/<int:cid>/', CourseDetail.as_view(), name='course-detail'),
    path('video/<int:vid>/', VideoDetail.as_view(), name='video-detail'),
    path('search/', course_search, name='course-search'),
    path('upload/', UploadCourse.as_view()),
    path('video/upload/', UploadVideo.as_view()),
]

services/urls.py
# encoding: utf-8
"""
@author: Sunmouren
@contact: sunxuechao1024@gmail.com
@time: 2019/2/16 15:26
@desc: 
"""

from django.urls import path

from .views import ServiceList, ServiceDetail, UploadService

app_name = 'services'


urlpatterns = [
    path('list/', ServiceList.as_view(), name='service-list'),
    path('detail/<int:sid>/', ServiceDetail.as_view(), name='service-detail'),
    path('upload/', UploadService.as_view()),
]

zw_online/urls.py
from django.conf import settings
from django.contrib import admin
from django.http import JsonResponse
from django.urls import path, include
from django.views.generic import TemplateView, View
from django.contrib.auth.mixins import LoginRequiredMixin

from qiniu import Auth


class GetQiNiuToken(LoginRequiredMixin, View):
    """
    获取七牛云的上传文件token
    """

    def get(self, request):
        try:
            q = Auth(settings.ACCESS_KEY, settings.SECRET_KEY)
            token = q.upload_token(bucket=settings.BUCKET_NAME, key=None, expires=3600)

            return JsonResponse({'msg': 'ok', 'token': token, 'username': request.user.username})
        except BaseException:
            return JsonResponse({'msg': 'ko'})


urlpatterns = [
    path('admin/', admin.site.urls),
    # index
    path('', TemplateView.as_view(template_name='index.html', extra_context={'current_page': 'index'}), name='index'),
    # service
    path('service/', include('services.urls', namespace='services')),
    # course
    path('course/', include('courses.urls', namespace='courses')),
    # banner
    path('banner/', include('banners.urls', namespace='banners')),
    # abouts
    path('about/', include('abouts.urls', namespace='abouts')),
    # upload token
    path('upload/token/', GetQiNiuToken.as_view()),

]

templates/about-us.html
{% extends 'base.html' %}


{% block title %}
    关于我们
{% endblock %}


{% block content %}
    <div class="row">
        <div class="col-md-10 offset-md-1">
            <div class="my-3 p-3 bg-white rounded box-shadow">
                <h6 class="border-bottom border-gray pb-2 mb-0">关于我们</h6>
                {% if about %}
                    <h5 class="mt-3 text-info">
                        {{ about.summary }}
                    </h5>
                    <h5 class="mt-3 text-info">
                        团队名称: {{ about.team_name }}

                    </h5>
                    <h5 class="mt-3 text-info">
                        服务宗旨: {{ about.purpose }}
                    </h5>
                    <h5 class="mt-3 text-info">
                        特色服务: {{ about.service }}
                    </h5>
                {% else %}
                    <h5 class="text-danger mt-3">
                        暂无内容
                    </h5>
                {% endif %}
            </div>
            <div class="my-3 p-3 bg-white rounded box-shadow">
                <h6 class="border-bottom border-gray pb-2 mb-0">联系我们</h6>
                <div class="row">
                    {% for image in qr_images %}
                        <div class="col-md-6">
                           <div class="card mt-3 text-center">
                               <img class="card-img-top text-center"  src="{{ image.img_url }}" alt="Card image cap">
                              <div class="card-body">
                                <h5 class="card-title text-truncate">{{ image.title }}</h5>
                              </div>
                           </div>
                        </div>
                    {% empty %}
                        <h5 class="mt-3 pl-3 text-danger">暂时无内容</h5>
                    {% endfor %}
                </div>
            </div>
        </div>
    </div>

{% endblock %}

templates/base.html
<!DOCTYPE html>
{% load static %}

<html lang="zh-cn">
	<head>
		<meta charset="UTF-8">
		<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
		<title>{% block title %}{% endblock %}</title>
		<!-- Bootstrap CSS -->
    	<link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}" />
        <link href="{% static 'css/font-awesome.min.css' %}" rel='stylesheet'>
        <link href="{% static 'css/animate.min.css' %}" rel='stylesheet'>
    	<link rel="stylesheet" href="{% static 'css/app.css' %}" />
        {% block css %}

        {% endblock %}
	</head>
	<body>
		<nav class="navbar navbar-expand-xl navbar-light bg-white fixed-top border border-top-0 border-right-0 border-left-0">
			<div class="container">
				<a class="navbar-brand text-danger" href="{% url 'index' %}"> <strong>IT掌上运维</strong> </a>
				<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
					<span class="navbar-toggler-icon"></span>
				</button>

			  	<div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <ul class="navbar-nav mr-auto">
                        <li class="nav-item">
                            <a class="nav-link {% ifequal 'index' current_page %}text-success{% endifequal %}"
                               href="{% url 'index' %}">
                                <i class="fa fa-home" aria-hidden="true"></i> 首页
                            </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link {% ifequal 'services' current_page %}text-success{% endifequal %}"
                               href="{% url 'services:service-list' %}">
                                <i class="fa fa-ravelry" aria-hidden="true"></i> 实战
                            </a>
                        </li>
                        <li class="nav-item">
                          <a class="nav-link {% ifequal 'courses' current_page %}text-success{% endifequal %}"
                             href="{% url 'courses:course-list' %}">
                              <i class="fa fa-book" aria-hidden="true"></i> 教程
                          </a>
                        </li>

<!--                         <li class="nav-item">
                          <a class="nav-link {% ifequal 'abouts' current_page %}text-success{% endifequal %}"
                             href="{% url 'abouts:about-us' %}">
                              <i class="fa fa-user-o" aria-hidden="true"></i> 关于我们
                          </a>
                        </li> -->
                    </ul>
<!--                     <form class="form-inline my-2 my-lg-0">
                        <a target="_blank" class="nav-link {% ifequal '' current_page %}text-success{% endifequal %}"
                             href="https://mp.weixin.qq.com/s/zeq1sTmaPsKt7Bsok0Ldrg">
                            <i class="fa fa-bandcamp" aria-hidden="true"></i> 软市场
                        </a>
                    </form> -->
			    </div>
			</div>
		</nav>

		<div class="main container mb-5" style="margin-top:74px">
            {% block content %}

            {% endblock %}
		</div>

        <div class="modal fade" id="orders-modal" tabindex="-1" role="dialog"  aria-hidden="true">
          <div class="modal-dialog modal-dialog-centered" role="document">
            <div class="modal-content">
              <div class="modal-header">
                <h5 class="modal-title" id="modalTitle"></h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                  <span aria-hidden="true">&times;</span>
                </button>
              </div>
              <div class="modal-body">
                <div class="review-form">
                    <div class="card border-0">
                        <div class="card-body pt-0">
                            <div class="card-subtitle">
                                 <div class="form-group">
                                    <label for="name" class="col-form-label">姓名</label>
                                    <input class="form-control" id="name">
                                 </div>
                                <div class="form-group">
                                    <label for="contact-way" class="col-form-label">联系方式</label>
                                    <select class="custom-select" id="contact-way">
                                        <option value="qq">QQ号</option>
                                        <option value="tel">手机号码</option>
                                    </select>
                                </div>
                                 <div class="form-group">
                                    <label for="contact-info" class="col-form-label">联系信息</label>
                                    <input class="form-control" id="contact-info" placeholder="请对应联系方式填写">
                                 </div>
                            </div>
                            <button data-sid="" class="card-link btn btn-outline-success float-right orders">
                                确认
                            </button>
                        </div>
                    </div>
                </div>
              </div>

            </div>
          </div>
        </div>

		<!-- Optional JavaScript -->
	    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
	    <script type="text/javascript" src="{% static 'js/jquery.min.js' %}"></script>
	    <script src="https://cdn.bootcss.com/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
	    <script src="https://cdn.bootcss.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
        <script src="{% static 'js/bootstrap-notify.min.js' %}" type="text/javascript"></script>
        <script type="text/javascript">
             $.ajaxSetup({
                data: {csrfmiddlewaretoken: '{{ csrf_token }}' }
             });
        </script>
        <script type="text/javascript" src="{% static 'upload/qiniu.min.js' %}"></script>
        <script type="text/javascript" src="{% static 'upload/md5.js' %}"></script>
        <script type="text/javascript" src="{% static 'js/app.js' %}"></script>
        {% block js %}

        {% endblock %}
	</body>
</html>

templates/course-detail.html
{% extends 'base.html' %}


{% block title %}
    课程详情
{% endblock %}


{% block content %}

    <div class="row">
        <div class="col-md-10 offset-md-1">
            {% if request.user.is_authenticated %}
                <div class="bg-light rounded  mb-3">
                    <button data-toggle="modal" data-target="#modal-upload-video"
                            class="btn btn-outline-info btn-block border-0">
                        <i class="fa fa-upload"></i> 上传视频
                    </button>
                </div>
            {% endif %}

            <div class="p-3 mb-3 bg-light rounded">
                <div class="d-flex justify-content-md-start align-items-center">
                    <div>
                        <a target="_blank" href="{{ course.img_url }}">
                            <img class="img-warp rounded box-shadow" alt="" src="{{ course.img_url }}?imageView2/1/w/156/h/100/q/75">
                        </a>
                    </div>
                    <div class="ml-3">
                        <h5>
                            <a href="{{ course.get_absolute_url }}" class="card-link">
                                {{ course.title }}
                            </a>
                        </h5>
                        <h6 class="">
                            {{ course.overview }}
                        </h6>
                        <span class="card-link small">
                            {{ course.get_video_count }} 个视频
                        </span>
                        <span class="card-link small">
                            {{ course.view_count }} 浏览量
                        </span>
                        <span class="card-link small">
                            {{ course.created }}
                        </span>
                    </div>
                </div>

            </div>

            <h6 class="mt-4">课程视频</h6>
            {% for video in videos %}
                <hr>
                {% include 'video-item.html' with video=video %}
            {% endfor %}
        </div>
    </div>


    <div class="modal fade bd-example-modal-lg" id="modal-upload-video" tabindex="-1" role="dialog" aria-hidden="true">
      <div class="modal-dialog modal-lg modal-dialog-centered" role="document">
        <div class="modal-content">
          <div class="modal-header">
            <h5 class="modal-title" id="exampleModalLongTitle">上传视频</h5>
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
              <span aria-hidden="true">&times;</span>
            </button>
          </div>
          <div class="modal-body">
            <div class="card border-0">
                <div class="card-body">
                    <div class="card-subtitle">
                         <div class="form-group">
                            <label for="title" class="col-form-label">视频标题</label>
                            <input class="form-control" id="title">
                         </div>
                        <div class="form-group">
                            <label for="overview" class="col-form-label">视频概述</label>
                            <textarea class="form-control" id="overview" rows="4"></textarea>
                         </div>
                         <div class="form-group">
                            <label for="video">视频文件</label>
                            <input type="file" class="form-control-file" id="video" accept="video/*">
                         </div>
                    </div>
                    <button data-cid="{{ course.id }}" class="card-link btn btn-outline-success float-right upload-video">
                        确认上传
                    </button>
                </div>
            </div>
          </div>
        </div>
      </div>
    </div>
{% endblock %}

{% block js %}
    <script type="text/javascript">
       $('button.upload-video').click(function () {

            var title = $.trim($('input#title').val());
            var overview = $.trim($('textarea#overview').val());

            if (title === '' || overview === ''){
                tips('标题、概述都不能为空~', 'danger');
                return false;
            }
            var file = $('input#video')[0].files[0];
            console.log(file);
            if (file === undefined){
                tips('视频不能为空~', 'danger');
                return false;
            }

            if (!/\.(mp4|MP4)$/.test(file.name)){
                 tips('请确认选择的是视频类型', 'danger');
                return false;
            }

            var cid = $(this).data('cid');

            $.ajax({
                cache: false,
                type: 'GET',
                url: '/upload/token/',
                success: function (response) {
                    if (response.msg === 'ok'){
                        var username = response.username;
                        var token = response.token;
                        var sort = 'video';
                        var postUrl = '/course/video/upload/';
                        var data = {'title': title, 'overview': overview, 'cid': cid, 'srcUrl': ''};
                        $('#modal-upload-video').hide();
                        // 显示页面加载圈圈
                        pageLoader('show');
                        uploadImageToQiNiu(file, username, token, sort, postUrl, data)
                    } else {
                        tips('上传失败~', 'danger');
                        setTimeout(function () {
                            location.reload();
                        }, 1500);
                    }
                }
            });

        });
    </script>
{% endblock %}

templates/course-item.html
<div class="d-flex justify-content-md-start align-items-center">
    <div>
        <a href="{{ course.get_absolute_url }}">
            <img class="img-warp rounded box-shadow" alt="" src="{{ course.img_url }}?imageView2/1/w/156/h/100/q/75">
        </a>
    </div>
    <div class="ml-3 text-truncate">
        <h5>
            <a href="{{ course.get_absolute_url }}" class="card-link">
                {{ course.title|truncatechars:40 }}
            </a>
        </h5>
        <h6 class="">
            {{ course.overview|truncatechars:40 }}
        </h6>
        <span class="card-link small">
            {{ course.get_video_count }} 个视频
        </span>
        <span class="card-link small">
            {{ course.view_count }} 浏览量
        </span>
        <span class="card-link small">
            {{ course.created }}
        </span>
    </div>
</div>

templates/course-list.html
{% extends 'base.html' %}


{% block title %}
    课程列表
{% endblock %}


{% block content %}
    <div class="row">
        <div class="col-md-10 offset-md-1">
            {% if request.user.is_authenticated %}
                <div class="bg-light rounded  mb-3">
                    <button data-toggle="modal" data-target="#modal-add-course"
                            class="btn btn-outline-info btn-block border-0">
                        <i class="fa fa-plus"></i> 添加教程
                    </button>
                </div>
            {% endif %}

            <h6 class="">全部教程</h6>

            {% for course in course_list %}
                <hr>
                {% include 'course-item.html' with course=course %}
            {% endfor %}
        </div>

    </div>



    <div class="modal fade bd-example-modal-lg" id="modal-add-course" tabindex="-1" role="dialog" aria-hidden="true">
      <div class="modal-dialog modal-lg modal-dialog-centered" role="document">
        <div class="modal-content">
          <div class="modal-header">
            <h5 class="modal-title" id="exampleModalLongTitle">添加教程</h5>
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
              <span aria-hidden="true">&times;</span>
            </button>
          </div>
          <div class="modal-body">
            <div class="card border-0">
                <div class="card-body">
                    <div class="card-subtitle">
                         <div class="form-group">
                            <label for="title" class="col-form-label">教程标题</label>
                            <input class="form-control" id="title">
                         </div>
                        <div class="form-group">
                            <label for="overview" class="col-form-label">教程概述</label>
                            <textarea class="form-control" id="overview" rows="4"></textarea>
                         </div>
                         <div class="form-group">
                            <label for="img">教程封面图</label>
                            <input type="file" class="form-control-file" id="img" accept="image/*">
                         </div>
                    </div>
                    <button data-sid="" class="card-link btn btn-outline-success float-right add-course">
                        确认添加
                    </button>
                </div>
            </div>
          </div>
        </div>
      </div>
    </div>

{% endblock %}

{% block js %}
    <script type="text/javascript">
       $('button.add-course').click(function () {

            var title = $.trim($('input#title').val());
            var overview = $.trim($('textarea#overview').val());
            if (title === '' || overview === ''){
                tips('标题、概述都不能为空~', 'danger');
                return false;
            }
            var file = $('input#img')[0].files[0];
            console.log(file);
            if (file === undefined){
                tips('教程封面图不能为空~', 'danger');
                return false;
            }

            if (!/\.(gif|jpg|jpeg|png|GIF|JPG|PNG)$/.test(file.name)){
                 tips('请确认选择的是图片类型', 'danger');
                return false;
            }

            $.ajax({
                cache: false,
                type: 'GET',
                url: '/upload/token/',
                success: function (response) {
                    if (response.msg === 'ok'){
                        var username = response.username;
                        var token = response.token;
                        var sort = 'courses';
                        var postUrl = '/course/upload/';
                        var data = {'title': title, 'overview': overview, 'srcUrl': ''};
                        $('#modal-add-course').hide();
                        // 显示页面加载圈圈
                        pageLoader('show');
                        uploadImageToQiNiu(file, username, token, sort, postUrl, data)
                    } else {
                        tips('上传失败~', 'danger');
                        setTimeout(function () {
                            location.reload();
                        }, 1500);
                    }
                }
            });

        });
    </script>
{% endblock %}

templates/index.html
{% extends 'base.html' %}

{% load static %}

{% load course_tags %}
{% load banner_tags %}
{% load service_tags %}

{% block title %}
    首页
{% endblock %}


{% block content %}

    <div class="row">
        <div class="col-md-10 offset-md-1">
            {% if request.user.is_authenticated %}
                <div class="bg-light rounded  mb-3">
                    <button data-toggle="modal" data-target="#modal-add-banner"
                            class="btn btn-outline-info btn-block border-0">
                        <i class="fa fa-plus"></i> 添加幻灯片
                    </button>
                </div>
            {% endif %}

            {% get_banners_list as banner_list %}


            {% if banner_list %}
                <div id="banner-list" class="carousel slide" data-ride="carousel">
                  <ol class="carousel-indicators">
                    {% for banner in banner_list %}
                        <li data-target="#banner-list"  data-slide-to="0" class="{% if forloop.first %}active{% endif %}"></li>
                    {% endfor %}
                  </ol>
                  <div class="carousel-inner box-shadow rounded">
                    {% for banner in banner_list %}
                        <div class="carousel-item {% if forloop.first %}active{% endif %}">
                            <a target="_blank" href="{{ banner.img_url }}">
                                <img class="d-block w-100"  src="{{ banner.img_url }}?imageView2/1/w/1150/h/400/q/75" alt="First slide">
                            </a>
                            <div class="carousel-caption d-none d-md-block">
                                <h1>{{ banner.title }}</h1>
                            </div>
                        </div>
                    {% endfor %}
                  </div>
                  <a class="carousel-control-prev" href="#banner-list" role="button" data-slide="prev">
                    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                    <span class="sr-only">Previous</span>
                  </a>
                  <a class="carousel-control-next" href="#banner-list" role="button" data-slide="next">
                    <span class="carousel-control-next-icon" aria-hidden="true"></span>
                    <span class="sr-only">Next</span>
                  </a>
                </div>
            {% endif %}


            <h6 class="mt-4">
                热门实战
                <a class="badge badge-light text-danger card-link float-right" href="{% url 'services:service-list' %}">全部实战</a>
            </h6>
            {% get_hot_service_list as service_list %}
            {% for service in service_list %}
                <hr>
                {% include 'service-item.html' with service=service %}
            {% endfor %}


            <h6 class="mt-5">
                热门教程
                <a class="badge badge-light text-danger card-link float-right" href="{% url 'courses:course-list' %}">全部教程</a>
            </h6>
            {% get_hot_course as course_list %}
            {% for course in course_list %}
                <hr>
                {% include 'course-item.html' with course=course %}
            {% endfor %}


            <div class="modal fade bd-example-modal-lg" id="modal-add-banner" tabindex="-1" role="dialog" aria-hidden="true">
              <div class="modal-dialog modal-lg modal-dialog-centered" role="document">
                <div class="modal-content">
                  <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLongTitle">添加幻灯片</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                      <span aria-hidden="true">&times;</span>
                    </button>
                  </div>
                  <div class="modal-body">
                    <div class="card border-0">
                        <div class="card-body">
                            <div class="card-subtitle">
                                 <div class="form-group">
                                    <label for="title" class="col-form-label">幻灯片标题</label>
                                    <input class="form-control" id="title">
                                 </div>
                                 <div class="form-group">
                                    <label for="img">图片</label>
                                    <input type="file" class="form-control-file" id="img" accept="image/*">
                                 </div>
                            </div>
                            <button data-sid="" class="card-link btn btn-outline-success float-right add-banner">
                                确认添加
                            </button>
                        </div>
                    </div>
                  </div>
                </div>
              </div>
            </div>
        </div>
    </div>


{% endblock %}


{% block js %}
    <script type="text/javascript">
       $('button.add-banner').click(function () {

            var title = $.trim($('input#title').val());
            if (title === ''){
                tips('标题不能为空~', 'danger');
                return false;
            }
            var file = $('input#img')[0].files[0];
            console.log(file);
            if (file === undefined){
                tips('图片不能为空~', 'danger');
                return false;
            }

            if (!/\.(gif|jpg|jpeg|png|GIF|JPG|PNG)$/.test(file.name)){
                 tips('请确认选择的是图片类型', 'danger');
                return false;
            }

            $.ajax({
                cache: false,
                type: 'GET',
                url: '/upload/token/',
                success: function (response) {
                    if (response.msg === 'ok'){
                        var username = response.username;
                        var token = response.token;
                        var sort = 'banners';
                        var postUrl = '/banner/upload/';
                        var data = {'title': title, 'srcUrl': ''};
                        $('#modal-add-banner').hide();
                        // 显示页面加载圈圈
                        pageLoader('show');
                        uploadImageToQiNiu(file, username, token, sort, postUrl, data)
                    } else {
                        tips('上传失败~', 'danger');
                        setTimeout(function () {
                            location.reload();
                        }, 1500);
                    }
                }
            });

        });
    </script>
{% endblock %}

templates/search.html
{% extends 'base.html' %}


{% block title %}
    搜索结果
{% endblock %}


{% block content %}
    {% with results.count as total_results %}
        <h6 class="border-bottom border-gray pb-2 mb-0">
            搜索关键字: <span class="text-danger">{{ query }}</span> <span class="float-right text-success">{{ total_results }} 个相关内容</span>
        </h6>
    {% endwith %}
    {% for course in results %}
        <div class="d-flex align-items-center p-2 my-3 text-white-50 bg-light rounded ">
            <div class="card border-0">
              <div class="card-body bg-light">
                <h5 class="card-title">{{ course.title }}</h5>
                <p class="card-text text-truncate">{{ course.overview }}</p>
                <span class="card-link">发布于: {{ course.created }}</span>
                <a target="_blank" href="{{ course.get_absolute_url }}" class="card-link">查看详情</a>
              </div>
            </div>
        </div>
    {% empty %}
        <div class="d-flex align-items-center p-2 my-3 text-white-50 bg-light rounded ">
            <h6 class="mb-0 lh-100">暂无相关内容</h6>
        </div>
    {% endfor %}

{% endblock %}

templates/service-detail.html
{% extends 'base.html' %}


{% block content %}

   <div class="row">
        <div class="col-md-10 offset-md-1">
            <div class="mb-3 bg-light rounded box-shadow p-3">
               <h4>
                     {{ service }}
               </h4>
                <h6 class="mt-2">
                     {{ service.overview }}
                </h6>
                <div class="mt-3">
                    <button data-toggle="modal"
                        data-target="#orders-modal"
                        data-sid="{{ service.id }}"
                        data-title="{{ service.title }}"
                        class="btn btn-outline-danger btn-sm card-link">立即实战</button>

<!--                     <span class="card-link">
                       价格: {{ service.price }} 元
                    </span> -->
                    <span class="card-link ">
                       {{ service.get_order_count }} 实战
                    </span>
                    <span class="card-link">
                        {{ service.view_count }} 浏览量
                    </span>
                </div>

            </div>
            <a target="_blank" href="{{ service.img_url }}">
                <img class="rounded box-shadow d-block w-100" src="{{ service.img_url }}?imageView2/1/w/1150/h/400/q/75" alt="">
            </a>


        </div>

   </div>
{% endblock %}